# Generated by Django 6.0.5 on 2026-05-22 15:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('cars', '0002_alter_carmodel_created_at_alter_carmodel_updated_at'),
        ('dealers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ListingModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to=settings.AUTH_USER_MODEL)),
                ('title', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('car', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cars.carmodel')),
                ('price', models.FloatField()),
                ('currency', models.CharField(choices=[('UAH', 'UAH'), ('USD', 'USD'), ('EUR', 'EUR')], default='UAH', max_length=3)),
                ('exchange_rate', models.JSONField()),
                ('region', models.CharField(
                    choices=[('Vinnytsia', 'Vinnytsia'), ('Volyn', 'Volyn'), ('Dnipropetrovsk', 'Dnipropetrovsk'), ('Donetsk', 'Donetsk'), ('Zhytomyr', 'Zhytomyr'),
                             ('Zakarpattia', 'Zakarpattia'), ('Zaporizhzhia', 'Zaporizhzhia'), ('Ivano-Frankivsk', 'Ivano-Frankivsk'), ('Kyiv', 'Kyiv'),
                             ('Kyiv region', 'Kyiv region'), ('Kirovohrad', 'Kirovohrad'), ('Luhansk', 'Luhansk'), ('Lviv', 'Lviv'), ('Mykolaiv', 'Mykolaiv'),
                             ('Odesa', 'Odesa'), ('Poltava', 'Poltava'), ('Rivne', 'Rivne'), ('Sumy', 'Sumy'), ('Ternopil', 'Ternopil'), ('Kharkiv', 'Kharkiv'),
                             ('Kherson', 'Kherson'), ('Khmelnytskyi', 'Khmelnytskyi'), ('Cherkasy', 'Cherkasy'), ('Chernivtsi', 'Chernivtsi'), ('Chernihiv', 'Chernihiv'),
                             ('Crimea', 'Crimea')], max_length=30)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('active', 'active'), ('inactive', 'inactive')], default='pending', max_length=10)),
                ('edit_attempts', models.IntegerField(default=0)),
                ('is_clean', models.BooleanField(default=True)),
                ('dealer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='listings', to='dealers.dealermodel')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'listings',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ListingStatsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('views_total', models.IntegerField(default=0)),
                ('views_daily', models.IntegerField(default=0)),
                ('views_weekly', models.IntegerField(default=0)),
                ('views_monthly', models.IntegerField(default=0)),
                ('avg_price_region', models.FloatField(blank=True, null=True)),
                ('avg_price_country', models.FloatField(blank=True, null=True)),
                ('listing', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='listings.listingmodel')),
            ],
            options={
                'db_table': 'listing_stats',
            },
        ),
    ]
