# Generated by Django 6.0.5 on 2026-05-28 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listingstatsmodel',
            name='last_view_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
