# Generated by Django 6.0.5 on 2026-05-22 18:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_alter_carmodel_created_at_alter_carmodel_updated_at'),
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listingmodel',
            name='car',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='cars.carmodel'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='listingmodel',
            name='currency',
            field=models.CharField(choices=[('UAH', 'UAH'), ('USD', 'USD'), ('EUR', 'EUR')], max_length=3),
        ),
        migrations.AlterField(
            model_name='listingmodel',
            name='exchange_rate',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
