# Generated by Django 6.0.5 on 2026-05-22 15:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DealerModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('region', models.CharField(choices=[('Vinnytsia', 'Vinnytsia'), ('Volyn', 'Volyn'), ('Dnipropetrovsk', 'Dnipropetrovsk'), ('Donetsk', 'Donetsk'), ('Zhytomyr', 'Zhytomyr'), ('Zakarpattia', 'Zakarpattia'), ('Zaporizhzhia', 'Zaporizhzhia'), ('Ivano-Frankivsk', 'Ivano-Frankivsk'), ('Kyiv', 'Kyiv'), ('Kyiv region', 'Kyiv region'), ('Kirovohrad', 'Kirovohrad'), ('Luhansk', 'Luhansk'), ('Lviv', 'Lviv'), ('Mykolaiv', 'Mykolaiv'), ('Odesa', 'Odesa'), ('Poltava', 'Poltava'), ('Rivne', 'Rivne'), ('Sumy', 'Sumy'), ('Ternopil', 'Ternopil'), ('Kharkiv', 'Kharkiv'), ('Kherson', 'Kherson'), ('Khmelnytskyi', 'Khmelnytskyi'), ('Cherkasy', 'Cherkasy'), ('Chernivtsi', 'Chernivtsi'), ('Chernihiv', 'Chernihiv'), ('Crimea', 'Crimea')], max_length=30)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'dealers',
            },
        ),
        migrations.CreateModel(
            name='DealerStaffModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('manager', 'Manager'), ('seller', 'Seller')], max_length=7)),
                ('dealer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff', to='dealers.dealermodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dealer_roles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'dealer_staff',
            },
        ),
    ]
