# Generated by Django 6.0.5 on 2026-05-19 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Profile',
            new_name='ProfileModel',
        ),
        migrations.AlterField(
            model_name='customusermodel',
            name='role',
            field=models.CharField(choices=[('buyer', 'Покупець'), ('seller', 'Продавець'), ('manager', 'Менеджер'), ('admin', 'Адміністратор')], max_length=7),
        ),
    ]
