# Generated by Django 6.0.5 on 2026-05-19 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_profile_profilemodel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customusermodel',
            name='previous_role',
            field=models.CharField(blank=True, choices=[('buyer', 'Покупець'), ('seller', 'Продавець'), ('manager', 'Менеджер'), ('admin', 'Адміністратор')], default=None, max_length=7, null=True),
        ),
    ]
