# Generated by Django 6.0.5 on 2026-05-20 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customusermodel_previous_role'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customusermodel',
            options={'ordering': ['id']},
        ),
    ]
